add_executable(test_barrier test_barrier.c)
set_source_files_properties(test_barrier.c PROPERTIES LANGUAGE C)
target_link_libraries(test_barrier PRIVATE lace::lace)
add_test(NAME test_barrier COMMAND test_barrier)

add_executable(test_together test_together.c)
set_source_files_properties(test_together.c PROPERTIES LANGUAGE C)
target_link_libraries(test_together PRIVATE lace::lace)
add_test(NAME test_together COMMAND test_together)
set_tests_properties(test_together PROPERTIES TIMEOUT 120)

add_executable(test_backoff test_backoff.c)
set_source_files_properties(test_backoff.c PROPERTIES LANGUAGE C)
target_link_libraries(test_backoff PRIVATE lace::lace)
add_test(NAME test_backoff COMMAND test_backoff)

add_executable(test_external test_external.c)
set_source_files_properties(test_external.c PROPERTIES LANGUAGE C)
target_link_libraries(test_external PRIVATE lace::lace)
add_test(NAME test_external COMMAND test_external)
