name: Linux

on: [push, pull_request]

jobs:
  gcc-build:
    name: 'Linux GCC-${{matrix.version}} ${{matrix.build_type}}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        version: [9, 12]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build gcc-${{matrix.version}} g++-${{matrix.version}}
    - name: Configure
      shell: bash
      run: |
        export CC=gcc-${{matrix.version}} CXX=g++-${{matrix.version}}
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DLACE_BUILD_TESTS=ON \
          -DLACE_BUILD_BENCHMARKS=ON
    - name: Build
      shell: bash
      run: cmake --build build
    - name: Test
      shell: bash
      run: ctest --test-dir build --output-on-failure -VV --timeout 60

  clang-build:
    name: 'Linux Clang-${{matrix.version}} ${{matrix.build_type}}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        version: [15, 19]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build clang-${{matrix.version}}
    - name: Configure
      shell: bash
      run: |
        export CC=clang-${{matrix.version}} CXX=clang++-${{matrix.version}}
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DLACE_BUILD_TESTS=ON \
          -DLACE_BUILD_BENCHMARKS=ON
    - name: Build
      shell: bash
      run: cmake --build build
    - name: Test
      shell: bash
      run: ctest --test-dir build --output-on-failure -VV --timeout 60

